### ISSUE TITLE
Invalid rich rule for forwarding everything from a source IP 

### ISSUE THREAD

**Issue by Smarre** [openSUSE/susefirewall2-to-firewalld#2]
I tried convert my old config consisting a custom zone and I got an error:

```
INFO: Enabling rich rule="rule family=ipv6 source address=2a01::/65 protocol value= accept" for zone=""
DEBUG: Executing: firewall-cmd --zone= --add-rich-rule=rule family=ipv6 source address=2a01:4f9:2a:56d::/65 protocol value= accept
Error: INVALID_RULE: internal error in _lexer(): value=
FIREWALLD ERROR: Command 'firewall-cmd ' failed
```
[susefirewall2-to-firewalld -c -d output](https://github.com/openSUSE/susefirewall2-to-firewalld/files/2048106/log.txt)

It seems to be related to

```
FW_FORWARD="2a01::/65,::/0 ::/0,2a01::/65"

as emptying that makes the error disappear.

**Comment by hwoarang** [comment]
Thank you for the report @Smarre . This case is not handled by the script at all right now. It should be possible to add it.

**Comment by hwoarang** [comment]
@Smarre would you be able to try https://github.com/hwoarang/susefirewall2-to-firewalld/commit/2f96b02607dfaa9a0388c4bb0f4c1ce263482590 ? A bit of warning though that the script can't handle unknown zones (like your 'vpn' one). It can only handle ext/dmz/int and only a subject of rules of course. Handling user-defined zones is currently out of scope so you would need to migrate these yourself.

**Comment by Smarre** [comment]
@hwoarang Thanks for quick fix. I tested it, it passes further with the change.

There is another another problem later (should I do another ticket?):

```
DEBUG: Executing: firewall-cmd --direct --add-passthrough ipv4 -t filter -A -i tun0 -j input_vpn
Error: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: Bad argument `tun0'
Error occurred at line: 2
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
```
I know that the custom zones are not supported, IIRC it’s been well said in different places. I guess it doesn’t make sense to implement that feature since need for it is small, but it’s nice to get the script run through without problems so I only need to add the extra custom things. That said, I already converted my own system, but I guess others having similar problems should be benefit from this too. If you need more help with testing, I’m available :)

**Comment by hwoarang** [comment]
@Smarre Thank you for your help. I have updated the script to warn about unknown chain.

https://github.com/hwoarang/susefirewall2-to-firewalld/tree/bug%232

Please give it a go when you have the time.

**Comment by Smarre** [comment]
@hwoarang I tested it and it passes without problems now. Is the warning you’re talking about ```DEBUG: Inverted rules are being ignored!```?

**Comment by hwoarang** [comment]
@Smarre Thanks for testing. No, this warning exists already in your logs. The new warning should say something like this

`warn "MIGRATION: '-A INPUT -i tun0 -j input_vpn'  will not be migrated to FirewallD"`

you should be able to see similar warnings for every iptables rule which operates in the vpn zones.

**Comment by Smarre** [comment]
@hwoarang Okay thanks, I got the warning. I was missing ```-v``` in addition to ```-d``` to get warnings out :)

**Comment by hwoarang** [comment]
Thanks for testing. I will merge the changes now

**Comment by Smarre** [comment]
No problems.
